// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {main} from '../models';

export function ClearLogs():Promise<void>;

export function GetConfig():Promise<config.Config>;

export function GetConfigPath():Promise<string>;

export function GetWorkPaths():Promise<Record<string, string>>;

export function GetLogs():Promise<Array<main.LogEntry>>;

export function GetStatus():Promise<main.Status>;

export function Minimize():Promise<void>;

export function Quit():Promise<void>;

export function Restart():Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function Start():Promise<void>;

export function Stop():Promise<void>;

export function ToggleMaximize():Promise<void>;
