// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConfigPath() {
  return window['go']['main']['App']['GetConfigPath']();
}

export function GetWorkPaths() {
  return window['go']['main']['App']['GetWorkPaths']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function Minimize() {
  return window['go']['main']['App']['Minimize']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function Restart() {
  return window['go']['main']['App']['Restart']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function Start() {
  return window['go']['main']['App']['Start']();
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}

export function ToggleMaximize() {
  return window['go']['main']['App']['ToggleMaximize']();
}
